### ISSUE TITLE
Cannot install based on readme instructions

### ISSUE THREAD

**Issue by blooop** [theodo/ticket-dependency-graph#36]
I am running inside a docker container because of compatibility issues with npm and ROS.

I had to add the registry line to fix another error:
```
    npm config set registry http://registry.npmjs.org/  
    npm install
    npm start
```
but that gives these errors.  Any idea of what is going on? Sorry, its my first time with npm.   I checked the npm install command and it does not require args hence I'm not sure what EMISSINGARG is referring to. 
```
loadDevDep:webpack-dev-se / |################################################-----------------------------------------------------------------------------------------------------|
loadDevDep:webpack-dev-se / |################################################-----------------------------------------------------------------------------------------------------|
npm ERR! Linux 5.4.0-62-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /work/npm-debug.log

> ticket-dependency-graph@1.0.0 start /work
> webpack-dev-server --colors

sh: 1: webpack-dev-server: not found

npm ERR! Linux 5.4.0-62-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ticket-dependency-graph@1.0.0 start: `webpack-dev-server --colors`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ticket-dependency-graph@1.0.0 start script 'webpack-dev-server --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ticket-dependency-graph package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ticket-dependency-graph
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ticket-dependency-graph
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /work/npm-debug.log
finished running docker, cleaning up...
```

For completeness this is my dockerfile:
```
FROM ubuntu:18.04
RUN apt-get update || true && apt-get install -y --no-install-recommends nodejs-dev node-gyp libssl1.0-dev npm && apt-get clean && rm -rf /var/lib/apt/lists/* 
```
And this is script called runInDocker.sh launches the docker image and runs the npm install commands:
```
#!/bin/bash

if [[ -v INSIDEDOCKER ]]; then #everything in this block is run inside the docker container
    echo "Run inside docker..."
    cd work
    ls -l 
    npm config set registry http://registry.npmjs.org/  
    npm install
    npm start
else 
    echo "Building docker image..." #image named depgraphdocker
    docker build -t depgraphdocker .
    #set up volume linking current working directory
    #run the same script but inside docker and pass the same args to the script
    #with --env set an environment variable so the script knows it is inside docker
    docker run -it --rm --env INSIDEDOCKER=1 -v `pwd`:/work depgraphdocker /work/runInDocker.sh 
fi
```
Thanks

**Comment by blooop** [comment]
apologies, if I change the docker image to node:14 installs correctly.
